sudo: required
language: ruby
services: [docker]
cache:
  bundler: true
  # directories:
  #   - node_modules
  # yarn: true
before_install:
  - docker-compose build
before_script:
  - docker-compose run web -e RAILS_ENV=test rails db:setup
script:
  - docker-compose run web rspec
  - docker-compose run web cucumber
# services:
#   - postgresql
# before_install:
#   - gem update --system # see https://github.com/travis-ci/travis-ci/issues/8978
# install:
#   - bundle install --jobs=3 --retry=3 --deployment
#   - yarn install
# before_script:
#   - RAILS_ENV=test bundle exec rake db:setup
# script:
#   - bundle exec rspec
#   - bundle exec cucumber
