sudo: required
services: [docker]
cache:
  bundler: true
  # directories:
  #   - node_modules
  # yarn: true
env:
  - DOCKER_POSTGRES_PASSWORD=c02aaadbdb5c592f55dccbe4b115faa828878afe5f5b5634d33127d20670d1dc563e8dc71918a902cb0277d6767c93cbdbd89dcc77da2c77d422f5cf3c9b3b6f DOCKER_APP_DB_USERNAME=contraq DOCKER_APP_DB_PASSWORD=fe4c6960edc296e2e5e81689f39d2048b2e66cd23a4266efbcd683e32e8d36fdd92269d80d9de15c15cfa7e8e7f48890015a43d5594ab5355bd9f78777830b62
before_install:
  - docker-compose build
before_script:
  - docker-compose up
  - docker-compose run -e RAILS_ENV=test web rails db:setup
script:
  - docker-compose run web rspec
  - docker-compose run web cucumber
# services:
#   - postgresql
# before_install:
#   - gem update --system # see https://github.com/travis-ci/travis-ci/issues/8978
# install:
#   - bundle install --jobs=3 --retry=3 --deployment
#   - yarn install
# before_script:
#   - RAILS_ENV=test bundle exec rake db:setup
# script:
#   - bundle exec rspec
#   - bundle exec cucumber
