language: ruby
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
services:
  - postgresql
install:
  - bundle install --jobs=3 --retry=3 --deployment
  - yarn install
before_script:
  - RAILS_ENV=test bundle exec rake db:setup
script:
  - bundle exec rspec
  - bundle exec cucumber
