version: "3.2"
services:
  web:
    environment:
      CUCUMBER_FORMAT: ${CUCUMBER_FORMAT}
      CUCUMBER_EXTRA_OPTIONS: ${CUCUMBER_EXTRA_OPTIONS}
    volumes:
      - ".:/contraq"
    tty: true
    stdin_open: true
  db:
    volumes:
      - "./.pg_data:/var/lib/postgresql/data"
